<?php
// +----------------------------------------------------------------------
// | 前端主题配置
// +----------------------------------------------------------------------

return array (
  'color_primary' => '#0078d4',
  'color_success' => '#67C23A',
  'color_warning' => '#E6A23C',
  'color_danger' => '#F56C6C',
  'color_info' => '#909399',
  'color_bg_color' => '#f3f3f3',
  'color_text_color' => '#1a1a1a',
  'color_text_color_secondary' => '#5f5f5f',
  'color_border_color' => 'rgba(0, 0, 0, 0.08)',
  'color_header_bg' => 'rgba(243, 243, 243, 0.85)',
  'color_footer_bg' => '#f3f3f3',
  'color_footer_text' => '#5f5f5f',
  'color_card_bg' => 'rgba(255, 255, 255, 0.7)',
  'color_price_color' => '#ff4d4f',
  'color_vip_color' => '#faad14',
  'dark_color_primary' => '#0078d4',
  'dark_color_success' => '#67C23A',
  'dark_color_warning' => '#E6A23C',
  'dark_color_danger' => '#F56C6C',
  'dark_color_info' => '#909399',
  'dark_color_bg_color' => '#202020',
  'dark_color_text_color' => '#ffffff',
  'dark_color_text_color_secondary' => '#cccccc',
  'dark_color_border_color' => 'rgba(255, 255, 255, 0.08)',
  'dark_color_header_bg' => 'rgba(32, 32, 32, 0.85)',
  'dark_color_footer_bg' => '#202020',
  'dark_color_footer_text' => '#cccccc',
  'dark_color_card_bg' => 'rgba(44, 44, 44, 0.7)',
  'dark_color_price_color' => '#ff4d4f',
  'dark_color_vip_color' => '#faad14',
  'layout_header_fixed' => true,
  'layout_sidebar_collapse' => false,
  'layout_show_footer' => true,
  'layout_container_width' => '1200px',
  'layout_header_height' => '48px',
  'layout_sidebar_width' => '240px',
  'layout_border_radius' => '8px',
  'layout_card_padding' => '24px',
  'layout_grid_gap' => '16px',
  'layout_section_padding' => '64px',
  'feature_dark_mode' => true,
  'feature_rtl_support' => false,
  'feature_multi_language' => true,
  'feature_seo_optimized' => true,
  'feature_lazy_load' => true,
  'feature_infinite_scroll' => false,
  'feature_show_views' => true,
  'feature_show_likes' => true,
  'feature_enable_search' => true,
  'feature_enable_register' => true,
  'feature_enable_comment' => true,
  'effect_backdrop_blur' => '20px',
  'effect_backdrop_saturate' => '125%',
  'effect_shadow_card' => '0 2px 8px rgba(0, 0, 0, 0.04)',
  'effect_shadow_card_hover' => '0 8px 24px rgba(0, 0, 0, 0.08)',
  'effect_shadow_dialog' => '0 32px 64px rgba(0, 0, 0, 0.18)',
  'effect_transition_fast' => '0.1s ease',
  'effect_transition_normal' => '0.2s ease',
  'effect_transition_slow' => '0.3s ease',
  'typo_font_family' => '\'Segoe UI Variable\', \'Segoe UI\', -apple-system, BlinkMacSystemFont, \'PingFang SC\', \'Microsoft YaHei\', sans-serif',
  'typo_font_size_base' => '14px',
  'typo_font_size_small' => '13px',
  'typo_font_size_large' => '16px',
  'typo_line_height' => '1.5',
  'theme' => 'default',
);
